remote_theme: LeNPaul/Millennial@main
plugins:
- jekyll-remote-theme

title: Sports Equipment Recognizer 
description: An image classification API that classifies 20 different sports equipments

author:
  name: Tanvir Ahmed Munna