remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-paginate

title: Sports Equipment Recognizer
description: An image classification API that classifies 20 different sports equipments

author:
  name: Tanvir Ahmed Munna